### ISSUE TITLE
Create web UI

### ISSUE THREAD

**Issue by katzuv** [katzuv/covid-whatsapp-bot#6]
We will use [Bootstrap](https://getbootstrap.com/).

**Comment by leibovichrotem** [comment]
- classic and flexible form
- form labels:
    - unit
    - department
    - full name
    - id
    - personal number
    - phone number
    - rank
    - test reason
    - test date
    - result date
- form submit
- post values to web server

**Comment by noga-malka** [comment]
add two fields:
* team leader name
* team leader phone number
